
CREATE TABLE PROYECTODB.TBL_CLIENTES
(
    CLIENTE_ID VARCHAR2(20) NOT NULL,
    PRIMER_NOMBRE VARCHAR2(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(50),
    PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50),
    IDENTIFICACION NUMBER(15) NOT NULL,
    DIRECCION VARCHAR2(50)
)TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_CLIENTES IS 'Tabla de clientes';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.CLIENTE_ID IS 'ID del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.PRIMER_NOMBRE IS 'Primer nombre del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.SEGUNDO_NOMBRE IS 'Segundo nombre del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.PRIMER_APELLIDO IS 'Primer apellido del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.SEGUNDO_APELLIDO IS 'Segundo apellido del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.IDENTIFICACION IS 'Identificación del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CLIENTES.DIRECCION IS 'Dirección del cliente'; 

CREATE UNIQUE INDEX IDX_UNIQUE_CLIENTE_ID
    ON PROYECTODB.TBL_CLIENTES(CLIENTE_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_CLIENTES ADD CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (CLIENTE_ID)
    USING INDEX IDX_UNIQUE_CLIENTE_ID;


CREATE TABLE PROYECTODB.TBL_TIPO_PARAMETROS
(
    TIPO_PARAMETRO_ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    VALOR NUMBER(10) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL
) TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_TIPO_PARAMETROS IS 'Tabla de parámetros';
COMMENT ON COLUMN PROYECTODB.TBL_TIPO_PARAMETROS.TIPO_PARAMETRO_ID IS 'ID del tipo de parámetro';
COMMENT ON COLUMN PROYECTODB.TBL_TIPO_PARAMETROS.NOMBRE IS 'Nombre del parámetro';
COMMENT ON COLUMN PROYECTODB.TBL_TIPO_PARAMETROS.VALOR IS 'Valor del parámetro';
COMMENT ON COLUMN PROYECTODB.TBL_TIPO_PARAMETROS.DESCRIPCION IS 'Descripción del parámetro';

CREATE UNIQUE INDEX IDX_UNIQUE_TIPO_PARAMETRO_ID
    ON PROYECTODB.TBL_TIPO_PARAMETROS(TIPO_PARAMETRO_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_TIPO_PARAMETROS ADD CONSTRAINT PK_TIPO_PARAMETRO_ID PRIMARY KEY (TIPO_PARAMETRO_ID)
    USING INDEX IDX_UNIQUE_TIPO_PARAMETRO_ID;


CREATE TABLE PROYECTODB.TBL_CUENTAS
(
    CUENTA_ID       VARCHAR2(20) NOT NULL,
    CLIENTE_ID      VARCHAR2(20) NOT NULL,
    TIPO_CUENTA_ID  NUMBER(10)   NOT NULL,
    ESTADO_ID       NUMBER(10)   DEFAULT 1 NOT NULL,
    SALDO           NUMBER(15,2) DEFAULT 0 NOT NULL
) TABLESPACE PROYECTO_DAT;


COMMENT ON TABLE PROYECTODB.TBL_CUENTAS IS 'Tabla de cuentas';
COMMENT ON COLUMN PROYECTODB.TBL_CUENTAS.CUENTA_ID IS 'ID de la cuenta';
COMMENT ON COLUMN PROYECTODB.TBL_CUENTAS.CLIENTE_ID IS 'ID del cliente';
COMMENT ON COLUMN PROYECTODB.TBL_CUENTAS.TIPO_CUENTA_ID IS 'ID del tipo de cuenta';
COMMENT ON COLUMN PROYECTODB.TBL_CUENTAS.ESTADO_ID IS 'ID del estado de la cuenta';
COMMENT ON COLUMN PROYECTODB.TBL_CUENTAS.SALDO IS 'Saldo de la cuenta';


CREATE UNIQUE INDEX IDX_UNIQUE_CUENTA_ID
    ON PROYECTODB.TBL_CUENTAS (CUENTA_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_CUENTAS 
    ADD CONSTRAINT PK_CUENTA_ID 
    PRIMARY KEY (CUENTA_ID)
    USING INDEX IDX_UNIQUE_CUENTA_ID;


-- Índice para CLIENTE_ID
CREATE INDEX IDX_CLIENTE_ID
    ON PROYECTODB.TBL_CUENTAS (CLIENTE_ID)
    TABLESPACE PROYECTO_IDX;

-- FK hacia TBL_CLIENTES
ALTER TABLE PROYECTODB.TBL_CUENTAS 
    ADD CONSTRAINT FK_CLIENTE_ID 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES PROYECTODB.TBL_CLIENTES (CLIENTE_ID);

-- Índice para TIPO_CUENTA_ID
CREATE INDEX IDX_TIPO_CUENTA_ID
    ON PROYECTODB.TBL_CUENTAS (TIPO_CUENTA_ID)
    TABLESPACE PROYECTO_IDX;

-- FK hacia TBL_TIPO_PARAMETROS (TIPO CUENTA)
ALTER TABLE PROYECTODB.TBL_CUENTAS 
    ADD CONSTRAINT FK_TIPO_CUENTA_ID 
    FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES PROYECTODB.TBL_TIPO_PARAMETROS (TIPO_PARAMETRO_ID);

-- Índice para ESTADO_ID
CREATE INDEX IDX_ESTADO_ID
    ON PROYECTODB.TBL_CUENTAS (ESTADO_ID)
    TABLESPACE PROYECTO_IDX;

-- FK hacia TBL_TIPO_PARAMETROS (ESTADO)
ALTER TABLE PROYECTODB.TBL_CUENTAS 
    ADD CONSTRAINT FK_ESTADO_ID 
    FOREIGN KEY (ESTADO_ID)
    REFERENCES PROYECTODB.TBL_TIPO_PARAMETROS (TIPO_PARAMETRO_ID);

CREATE TABLE PROYECTODB.TBL_TRANSACCIONES
(
    TRANSACCION_ID NUMBER NOT NULL,
    CUENTA_ID VARCHAR2(20) NOT NULL,
    TIPO_TRANSACCION_ID NUMBER(10) NOT NULL,
    MONTO NUMBER(15,2) NOT NULL,
    FECHA_TRANSACCION DATE DEFAULT SYSDATE NOT NULL 
) TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_TRANSACCIONES IS 'Tabla de transacciones';
COMMENT ON COLUMN PROYECTODB.TBL_TRANSACCIONES.TRANSACCION_ID IS 'ID de la transaccion';
COMMENT ON COLUMN PROYECTODB.TBL_TRANSACCIONES.CUENTA_ID IS 'ID de la cuenta';
COMMENT ON COLUMN PROYECTODB.TBL_TRANSACCIONES.TIPO_TRANSACCION_ID IS 'ID del tipo de transaccion';
COMMENT ON COLUMN PROYECTODB.TBL_TRANSACCIONES.MONTO IS 'Monto de la transaccion';
COMMENT ON COLUMN PROYECTODB.TBL_TRANSACCIONES.FECHA_TRANSACCION IS 'Fecha de la transaccion';

CREATE UNIQUE INDEX IDX_UNIQUE_TRANSACCION_ID
    ON PROYECTODB.TBL_TRANSACCIONES(TRANSACCION_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_TRANSACCIONES ADD CONSTRAINT PK_TRANSACCION_ID PRIMARY KEY (TRANSACCION_ID)
    USING INDEX IDX_UNIQUE_TRANSACCION_ID;

CREATE INDEX IDX_CUENTA_ID
    ON PROYECTODB.TBL_TRANSACCIONES(CUENTA_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_TRANSACCIONES ADD CONSTRAINT FK_CUENTA_ID FOREIGN KEY (CUENTA_ID)
    REFERENCES PROYECTODB.TBL_CUENTAS(CUENTA_ID);

CREATE INDEX IDX_TIPO_TRANSACCION_ID
    ON PROYECTODB.TBL_TRANSACCIONES(TIPO_TRANSACCION_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_TRANSACCIONES ADD CONSTRAINT FK_TIPO_TRANSACCION_ID FOREIGN KEY (TIPO_TRANSACCION_ID)
    REFERENCES PROYECTODB.TBL_TIPO_PARAMETROS(TIPO_PARAMETRO_ID);



CREATE TABLE PROYECTODB.TBL_ROLES
(
    ROL_ID NUMBER(3) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL UNIQUE
) TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_ROLES IS 'Tabla de roles';
COMMENT ON COLUMN PROYECTODB.TBL_ROLES.ROL_ID IS 'ID del rol';
COMMENT ON COLUMN PROYECTODB.TBL_ROLES.NOMBRE IS 'Nombre del rol';

CREATE UNIQUE INDEX IDX_UNIQUE_ROL_ID
    ON PROYECTODB.TBL_ROLES(ROL_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_ROLES ADD CONSTRAINT PK_ROL_ID PRIMARY KEY (ROL_ID)
    USING INDEX IDX_UNIQUE_ROL_ID;



CREATE TABLE PROYECTODB.TBL_USUARIOS
(
    USUARIO_ID NUMBER NOT NULL,
    ROL_ID NUMBER(3) NOT NULL,
    CLIENTE_ID VARCHAR2(20),
    USUARIO VARCHAR2(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(20) NOT NULL
) TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_USUARIOS IS 'Tabla de usuarios';
COMMENT ON COLUMN PROYECTODB.TBL_USUARIOS.USUARIO_ID IS 'ID del usuario';
COMMENT ON COLUMN PROYECTODB.TBL_USUARIOS.ROL_ID IS 'ID del rol';
COMMENT ON COLUMN PROYECTODB.TBL_USUARIOS.USUARIO IS 'Usuario';
COMMENT ON COLUMN PROYECTODB.TBL_USUARIOS.PASSWORD IS 'Contraseña';

CREATE UNIQUE INDEX IDX_UNIQUE_USUARIO_ID
    ON PROYECTODB.TBL_USUARIOS(USUARIO_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_USUARIOS ADD CONSTRAINT PK_USUARIO_ID PRIMARY KEY (USUARIO_ID)
    USING INDEX IDX_UNIQUE_USUARIO_ID;

CREATE INDEX IDX_ROL_ID
    ON PROYECTODB.TBL_USUARIOS(ROL_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_USUARIOS ADD CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID)
    REFERENCES PROYECTODB.TBL_ROLES(ROL_ID);

CREATE INDEX IDX_CLIENTE_ID_USUARIOS
    ON PROYECTODB.TBL_USUARIOS(CLIENTE_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_USUARIOS ADD CONSTRAINT FK_CLIENTE_ID_USUARIOS FOREIGN KEY (CLIENTE_ID)
    REFERENCES PROYECTODB.TBL_CLIENTES(CLIENTE_ID);




CREATE TABLE PROYECTODB.TBL_AUDITORIA_TRANSACCIONES
(
    AUDITORIA_ID NUMBER NOT NULL,
    TRANSACCION_ID NUMBER NOT NULL,
    USUARIO_ID NUMBER NOT NULL,
    FECHA_OPERACION DATE NOT NULL
) TABLESPACE PROYECTO_DAT;

COMMENT ON TABLE PROYECTODB.TBL_AUDITORIA_TRANSACCIONES IS 'Tabla de auditoria de transacciones';
COMMENT ON COLUMN PROYECTODB.TBL_AUDITORIA_TRANSACCIONES.AUDITORIA_ID IS 'ID de la auditoria';
COMMENT ON COLUMN PROYECTODB.TBL_AUDITORIA_TRANSACCIONES.TRANSACCION_ID IS 'ID de la transaccion';
COMMENT ON COLUMN PROYECTODB.TBL_AUDITORIA_TRANSACCIONES.USUARIO_ID IS 'Usuario que realiza la transaccion';
COMMENT ON COLUMN PROYECTODB.TBL_AUDITORIA_TRANSACCIONES.FECHA_OPERACION IS 'Fecha de la transaccion';

CREATE UNIQUE INDEX IDX_UNIQUE_AUDITORIA_ID
    ON PROYECTODB.TBL_AUDITORIA_TRANSACCIONES(AUDITORIA_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_AUDITORIA_TRANSACCIONES ADD CONSTRAINT PK_AUDITORIA_ID PRIMARY KEY (AUDITORIA_ID)
    USING INDEX IDX_UNIQUE_AUDITORIA_ID;

CREATE INDEX IDX_TRANSACCION_ID
    ON PROYECTODB.TBL_AUDITORIA_TRANSACCIONES(TRANSACCION_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_AUDITORIA_TRANSACCIONES ADD CONSTRAINT FK_TRANSACCION_ID FOREIGN KEY (TRANSACCION_ID)
    REFERENCES PROYECTODB.TBL_TRANSACCIONES(TRANSACCION_ID);

CREATE INDEX IDX_USUARIO
    ON PROYECTODB.TBL_AUDITORIA_TRANSACCIONES(USUARIO_ID)
    TABLESPACE PROYECTO_IDX;

ALTER TABLE PROYECTODB.TBL_AUDITORIA_TRANSACCIONES ADD CONSTRAINT FK_USUARIO FOREIGN KEY (USUARIO_ID)
    REFERENCES PROYECTODB.TBL_USUARIOS(USUARIO_ID);








