CREATE SEQUENCE SEQ_TRANSACCION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_AUDITORIA_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_USUARIO_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/